### ISSUE TITLE
System.NullReferenceException on FieldDeclarationSyntax

### ISSUE THREAD

**Issue by sievajetnamdar** [KirillOsenkov/RoslynQuoter#31]
Statement:

`private readonly string _leaseofferte = CarWise.Resources.GetString( "1" );
`
Stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.AddError[TNode](TNode node, ErrorCode code, Object[] args)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ConsumeUnexpectedTokens[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseStatement(String text, Int32 offset, ParseOptions options, Boolean consumeFullText)
   at QuoterService.Controllers.QuoterController.Get(String sourceText, NodeKind nodeKind, Boolean openCurlyOnNewLine, Boolean closeCurlyOnNewLine, Boolean preserveOriginalWhitespace, Boolean keepRedundantApiCalls, Boolean avoidUsingStatic)
```

**Comment by sievajetnamdar** [comment]
This can be parsed as a 'File' though

**Comment by KirillOsenkov** [comment]
Thanks, it's a known Roslyn bug. I should update soon.

**Comment by KirillOsenkov** [comment]
Fixed.
