### ISSUE TITLE
Parsing a `using` statement as a `member` throws NullRef.

### ISSUE THREAD

**Issue by otac0n** [KirillOsenkov/RoslynQuoter#48]
```
using System.Collections.Generic;
```

Parse as: `member`

```
Congratulations! You've found a bug in Quoter! Please open an issue at https://github.com/KirillOsenkov/RoslynQuoter/issues/new and paste the code you've typed above and this stack:

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at Quoter.QuotePropertyValues(SyntaxNode node) in C:\RoslynQuoter\src\Quoter\Quoter.cs:line 202
   at Quoter.QuoteNode(SyntaxNode node, String name) in C:\RoslynQuoter\src\Quoter\Quoter.cs:line 171
   at Quoter.Quote(Object treeElement, String name) in C:\RoslynQuoter\src\Quoter\Quoter.cs:line 163
   at Quoter.Quote(SyntaxNode node) in C:\RoslynQuoter\src\Quoter\Quoter.cs:line 125
   at QuoterService.Controllers.QuoterController.Get(String sourceText, NodeKind nodeKind, Boolean openCurlyOnNewLine, Boolean closeCurlyOnNewLine, Boolean preserveOriginalWhitespace, Boolean keepRedundantApiCalls, Boolean avoidUsingStatic, Boolean generateLINQPad) in C:\RoslynQuoter\src\Quoter.Web\Controllers\QuoterController.cs:line 39


P.S. Sorry!
```

---
P.S. No worries!

**Comment by bernd5** [comment]
It is fixed...

**Comment by KirillOsenkov** [comment]
Ah, yes, thank you!
