### ISSUE TITLE
Type aliases on predefined types are not supported

### ISSUE THREAD

**Issue by ltrzesniewski** [KirillOsenkov/RoslynQuoter#85]
> Congratulations! You've found a bug in Quoter!

Thank you, thank you! 🙂 

Here is the offending code, parsed as a regular file with default settings:

```csharp
using Foo = object;
```

And the error message:

```
Congratulations! You've found a bug in Quoter! Please open an issue at https://github.com/KirillOsenkov/RoslynQuoter/issues/new and paste the code you've typed above and this stack:System.Exception: Can't pick a method to call for UsingDirective.
If the first parameter is of type SyntaxKind, please add an exception for this node type in QuotePropertyValues().
   at RoslynQuoter.Quoter.InterpretMethodCall(Object instance, MethodCall methodCall) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 1326
   at RoslynQuoter.Quoter.InterpretApiCall(ApiCall apiCall) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 1237
   at RoslynQuoter.Quoter.Evaluate(ApiCall apiCall, Boolean normalizeWhitespace) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 1202
   at RoslynQuoter.Quoter.AddModifyingCall(ApiCall apiCall, MethodCall methodCall) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 1176
   at RoslynQuoter.Quoter.AddModifyingCalls(Object treeElement, ApiCall apiCall, List`1 values) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 1157
   at RoslynQuoter.Quoter.QuoteNode(SyntaxNode node, String name) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 197
   at RoslynQuoter.Quoter.Quote(Object treeElement, String name) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 183
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at RoslynQuoter.Quoter.QuoteList(IEnumerable syntaxList, String name) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 317
   at RoslynQuoter.Quoter.QuotePropertyValue(SyntaxNode node, PropertyInfo property) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 299
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at RoslynQuoter.Quoter.QuotePropertyValues(SyntaxNode node) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 253
   at RoslynQuoter.Quoter.QuoteNode(SyntaxNode node, String name) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 197
   at RoslynQuoter.Quoter.Quote(Object treeElement, String name) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 183
   at RoslynQuoter.Quoter.Quote(SyntaxNode node) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 151
   at RoslynQuoter.Quoter.QuoteText(String sourceText, NodeKind nodeKind) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter\Quoter.cs:line 83
   at QuoterService.Controllers.QuoterController.Post(QuoterRequestArgument arguments) in D:\a\RoslynQuoter\RoslynQuoter\src\Quoter.Web\Controllers\QuoterController.cs:line 66P.S. Sorry!
```

I found this when reporting https://github.com/dotnet/runtime/issues/110242

**Comment by KirillOsenkov** [comment]
Probably just need to update Roslyn to latest and run tests

**Comment by ltrzesniewski** [comment]
Ok, I can send an update to RoslynQuoter and SourceBrowser, but do you know when there'll be a stable Roslyn version?

![image](https://github.com/user-attachments/assets/e2488daf-9c79-451a-866e-15f3e6fdd86e)

That "final" thing cannot be taken seriously. It looks like `Roslyn - Copy (3) - Copy - Copy.sln` 😄 

![image](https://github.com/user-attachments/assets/9876fabe-a05d-42bc-bfdb-900c3b4afdd5)

**Comment by KirillOsenkov** [comment]
yeah I'm waiting myself, Jared said it should be out soonish
